### ISSUE TITLE
Run checkstyle checks on sources of sevntu.checkstyle

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#310]
When a new check is created a developer should run his check on the existing checks sources, analyze and fix violations.

The purpose of this issue it to automate this process by the following steps:
- Update maven build configuration for `sevntu-checks` module to run all checkstyle-checks.xml from Checkstyle repositoy on sources, as that is requirement for all checks that are going to appear in main repo.
- The build should failed until all the violations will be fixed

Think about how to enforce the developer to add his new check to the list of already running checks in order so the probable violations from this new check will be fixed by developer before pull request.

**Comment by damianszczepanik** [comment]
I've done it already for code coverage in https://github.com/damianszczepanik/sevntu.checkstyle/commit/a2f6734b0e3140021e56912e29fba8a264a98539 so I expect validating against checkstyle rules should work similar.

Have you prepared list of rules that shall be applied? I expect some of them are similar to Sonar but Sonar uses different approach and may check more than checkstyle (PMD, FindBugs).

We'd better start to clean #169 and then this one would be easier because we will not have exception for each class :)

**Comment by romani** [comment]
general idea - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-practice-what-you-preach , we failed to pass to GSoC 2015 so that idea will not be locked to one contributor, and we could start doing it.

right now we use - https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml config, but eventually all Checks should be added to it. We can do the same for sevntu.checkstyle.

**Comment by romani** [comment]
issue is already done https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L123
