### ISSUE TITLE
Eclipse update site wrong 

### ISSUE THREAD

**Issue by mbert** [sevntu-checkstyle/sevntu.checkstyle#857]
According to the documentation this URL should work:  https://sevntu-checkstyle.github.com/sevntu.checkstyle/update-site/
However it does not. When configuring it as an update site for Eclipse, it emits this error message:
```
No repository found at https://sevntu-checkstyle.github.com/sevntu.checkstyle/update-site/.
```
Tested with Eclipse Version: 2021-06 (4.20.0)

So either the update site is broken or the documentation is wrong.

**Comment by romani** [comment]
@rnveach , can you recheck in your eclipse ?

**Comment by rnveach** [comment]
See https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/856#issuecomment-877734372 which details the correct site and the fix we made.

@mbert Where are you saying our documentation is still wrong?

@romani I recommend adding an index page to our GH page in this folder to atleast say they hit the right location in their browser, and that they should give this location to Eclipse.

**Comment by rnveach** [comment]
@romani Scanning our code base, `http://sevntu-checkstyle.github.com/` seems like a wrong URL. It or `http://sevntu-checkstyle.github.com/sevntu.checkstyle` does not work, so we should change them.

I am seeing it being used multiple times in https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/eclipsecs-sevntu-plugin-feature/feature.xml .

**Comment by romani** [comment]
@mbert , can you send PR to fix wrong links

**Comment by nkavian** [comment]
Having `.com` instead of `.io` on the [Distribution page](https://sevntu-checkstyle.github.io/sevntu.checkstyle/#distribution) caused me to lose many hours of work.

![image](https://user-images.githubusercontent.com/1127421/130332277-f06290cc-958e-4261-b106-b5380afaa65a.png)

:(

**Comment by nkavian** [comment]
Although 1.40 SevNTU installs into Eclipse, the configuration menu is still empty. This is all very frustrating!

![image](https://user-images.githubusercontent.com/1127421/130332395-aac9442d-1288-49fe-aba8-cf52c550e33c.png)

**Comment by romani** [comment]
>caused me to lose many hours of work.

Sorry about this, please send Pull Request to fix it.

**Comment by rnveach** [comment]
Continuing on with https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857#issuecomment-906881832 ,

I am playing with this some to automate and it turns out for Checkstyle's meta generation to be integrated into sevntu, sevntu has to redo all it's javadocs to the format checkstyle wants. Checkstyle currently won't support any Checks that don't match this format and prints nothing by default (no descriptions or any properties).

As such, either the XML files have to be created fully manually now, which seems like a pointless undertaking, while it makes more sent for sevntu to redo all it's Javadocs to match checkstyle's requirements.

I am going to create a new issue for redoing the Javadocs with all the info here.

I am not seeing anything else needed in this issue and am closing it.

**Comment by rnveach** [comment]
While going down this rabbit hole further, I believe the break is not sevntu's fault. I am finding a few issues with eclipse-cs and it's handling of the new meta data and the ability to continue working with the old meta data. The old meta data code is still there, so it isn't clear yet why sevntu isn't working as is without change.

I have tested and found sevntu will work if eclipse-cs 8.35 or earlier is installed with the latest sevntu. I can't speak to how advisable it is to mis-match checkstyle versions like this, just noting what I have found so far.
