### ISSUE TITLE
upgrade minimal required jdk version to 11 and eclipse-cs 10.0.0

### ISSUE THREAD

**Issue by pbludov** [sevntu-checkstyle/sevntu.checkstyle#883]
To match https://github.com/checkstyle/checkstyle/issues/9146 this project should be upgraded too.

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
@romani @nrmancuso @pbludov Is sevntu really JDK 11?

Eclipse is still importing this as JDK 8.
Probably because we still have 1.8 references like https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L166 .
Our CI eclipse compiler still says 1.8. https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/.ci/eclipse-compiler-javac.sh#L42

We look incomplete here.

**Comment by romani** [comment]
ok,  better to remove all references to 1.8

**Comment by romani** [comment]
Merged
